PUT http://localhost:8686/server/user/
Content-Type: application/json

{
  "id": 45454554,
  "name": "Liza",
  "gender": "Сударыня",
  "preference": "Сударя",
  "description": "Ножи в кармане, вперед, россияне"
}

###
GET http://localhost:8686/server/user/16
Accept: application/json


}
###
