telegram:
  api-url: "https://api.telegram.org/"
  webhook-path: "https://9dce-178-207-154-253.ngrok.io"
  bot-name: "${NAME:ShippingShippingShippingbot}"
  bot-token: "${BOT_TOKEN}"
  host-url: "http://localhost:8686/server/user/"
spring:
  #    host: "<...>.compute-1.amazonaws.com"
  port: "8080"
  #    password:
  ssl: true
server:
  port: "8080"
